theme: jekyll-theme-slate
title: Adaptive
description: Adaptive is the platform companies use to transform into a place that manufactures awesome employees
show_downloads: false

github:
  is_project_page: false
