theme: jekyll-theme-slate
title: Adaptive Documentation
description: Adaptive is the platform companies use to create awesome teams
show_downloads: false
markdown: kramdown

github:
  is_project_page: false
  owner_name: Adaptive.Team
