theme: jekyll-theme-slate
title: Adaptive Documentation
description: Focus the power of collaboration to create sustainable change
show_downloads: false
markdown: kramdown

github:
  is_project_page: false
  owner_name: Adaptive.Team
